name: lr1experiment
version: 0.0.0.0
license: MIT

dependencies:
    - base >= 4.7 && < 5
    - containers
    - transformers
    - table-layout

default-extensions:
    - LambdaCase

ghc-options:
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints
    - -Wno-name-shadowing

executables:
    lr1experiment:
        source-dirs: src
        main: Main.hs
